# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3XE5gdj84FUhSWRJlhQqPf4yxxkv2jU
"""

# 1. تثبيت المكتبة الناقصة أولاً
!pip install xlsxwriter

import pandas as pd
from google.colab import files

def create_and_download_pro_excel():
    file_name = 'Electrical_Calculator_Final_2020.xlsx'

    # إعداد البيانات الأساسية
    data = {
        'مدخلات البيانات (أدخل أرقامك في هذا العمود)': [
            'مساحة الدور الواحد (م2)',
            'عدد الأدوار',
            'نوع المنشأة (سكنى=1 / تجارى=2)',
            'تصنيف الحي (قرية=1 / مدينة=2)',
            'طبيعة المنطقة (شعبى=1 / متوسط=2 / راقى=3)',
            'عدد المصاعد',
            'عدد طلمبات المياه',
            'المسافة عن مصدر التغذية (متر)'
        ],
        'القيم': [0, 0, 0, 0, 0, 0, 0, 0]
    }

    # إنشاء الملف ومعادلاته
    with pd.ExcelWriter(file_name, engine='xlsxwriter') as writer:
        df = pd.DataFrame(data)
        df.to_excel(writer, sheet_name='حاسبة التغذية الكهربائية', index=False)

        workbook  = writer.book
        worksheet = writer.sheets['حاسبة التغذية الكهربائية']

        # تنسيقات الألوان (أصفر للإدخال وأخضر للنتائج)
        fmt_header = workbook.add_format({'bold':True, 'bg_color':'#2F75B5', 'font_color':'white', 'border':1, 'align':'center'})
        fmt_input  = workbook.add_format({'bg_color':'#FFFFCC', 'border':1, 'align':'center'})
        fmt_result = workbook.add_format({'bold':True, 'bg_color':'#E2EFDA', 'border':1, 'align':'center'})

        worksheet.set_column('A:A', 45)
        worksheet.set_column('B:B', 20)
        worksheet.set_column('D:E', 35)

        # تحديد خلايا الإدخال باللون الأصفر
        for row in range(1, 9):
            worksheet.write(row, 1, 0, fmt_input)

        # إضافة قسم النتائج بالمعادلات (طبقاً لدليل 2020)
        worksheet.write('D1', 'النتائج (تتغير تلقائياً)', fmt_header)

        # مساحة إجمالية
        worksheet.write('D2', 'إجمالي المساحة الكلية (م2)')
        worksheet.write_formula('E2', '=B2*B3', fmt_result)

        # معادلة الحمل (صفحة 16 من الدليل)
        # تشمل المساحة والنشاط والموقع والمصاعد والطلمبات
        load_formula = (
            '=MAX(100, E2)/100 * '
            'IF(B5=1, IF(B4=1, 2, 5), '
            'IF(B6=3, 8, 4))'
            '+ (B7*9) + (B8*5)'
        )
        worksheet.write('D3', 'إجمالي الحمل المطلوب (ك.ف.أ)')
        worksheet.write_formula('E3', load_formula, fmt_result)

        # نوع المقايسة (نمطية أو فعلية)
        worksheet.write('D4', 'نوع المقايسة')
        worksheet.write_formula('E4', '=IF(AND(E3<=500, B9<=100), "نمطية (سعر موحد)", "فعلية (تفريد مهمات)")', fmt_result)

        # التكلفة (450 للنمطية وتقدير 1200 للفعلية شاملة الضرائب والرسوم)
        worksheet.write('D5', 'التكلفة الإجمالية التقديرية (جنية)')
        worksheet.write_formula('E5', '=IF(LEFT(E4,5)="نمطية", E3*450, E3*1200)', fmt_result)

        # شرط الغرفة (صفحة 19)
        worksheet.write('D6', 'موقف غرفة المحولات')
        worksheet.write_formula('E6', '=IF(OR(AND(B5=1, E3>100), AND(B5=2, E3>200)), "مطلوب توفير غرفة", "لا يشترط")', fmt_result)

    # التحميل التلقائي للملف
    print("✅ تم تثبيت المكتبات وإنشاء الشيت.. جاري التحميل الآن")
    files.download(file_name)

# تشغيل البرنامج
create_and_download_pro_excel()
